# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb80e26d844940957f59e899b02c4a17de4911e4abd5c0cf3426330ea44966f763b888d69888640010d1b9b626b4ea2fd8d2189538bd8a515cf996fdd1dfa552

test:
  secret_key_base: 427a13a74228e80ab1cb4cbd275f4bbc3cfcb611a3e00869feb39724aab25ee0edde9d6d23e019f361b0b5e0b3f319d02618212bc7bdba0ed73a05e0a85278cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
