# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20a2a944d5d37fdffb64396f6725495395733a944219df4fd2d14c126db142cc9671a71e004b80833c0dc8bf2d7cbb802593084acc8748db88cfcc3a6262cffc

test:
  secret_key_base: 7d3df0a200dafe7277ebbe6184f9e57eb27d98db3b2889a47b958521c5ab8129c2deb967fec2cf46499d5afe730965932b59dce073ebc8de93c1498fa34fcf2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
