# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4205d6da9230ab92f552af6c70693cdb706d4a0fa638bc1ecc8e00eaba387123d86251a273bd0e3f85e68a914aee7c54d4ebfceef3f03c6953fe37809c26be0

test:
  secret_key_base: 6476d995e5d8d7dd86a1b296709534722d4772813691f04df1bcd01e79b9a82361ace00b9f454b46421ea424721dc9b4cfbd70829511f9d3eb607435273dae7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
